Repository CAAPIM/gateway-developer-plugin, pull requests merged in 2018-09, with the labels that each got.

#64 Fix plugin build
  .gitignore
  build.gradle
  gateway-developer-plugin/build.gradle
  gateway-developer-plugin/settings.gradle
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloperBase.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/GatewayDeveloperPluginConfig.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageBuildException.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/Packager.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/BuildBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/GW7Builder.java
  gateway-developer-plugin/src/main/resources/META-INF/gradle-plugins/com.ca.apim.gateway.gateway-developer-plugin-base.properties
  gateway-developer-plugin/src/main/resources/META-INF/gradle-plugins/com.ca.apim.gateway.gateway-developer-plugin.properties
  gateway-developer-plugin/src/main/resources/scripts/apply-environment.sh
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/tasks/gw7/GW7BuilderTest.java
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/build.gradle
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/export/gateway/solution/config/services.yml
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/export/gateway/solution/policy/example project/example-project.xml
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/export/gateway/solution/policy/example project/example.xml
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/settings.gradle
  gateway-developer-plugin/src/test/resources/example-project/build.gradle
  gateway-developer-plugin/src/test/resources/example-project/lib/my-bundle-1.0.00.bundle
  gateway-developer-plugin/src/test/resources/example-project/settings.gradle
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/config/encass.yml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/config/identity-providers.yml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/config/policy-backed-services.yml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/config/services.yml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/config/static.properties
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/policy/example project/encass-policy.xml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/policy/example project/example-pbs.xml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/policy/example project/example-policy-include.xml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/policy/example project/example-project.xml
  gateway-developer-plugin/src/test/resources/example-project/src/main/gateway/policy/example project/example.xml
  gradle-plugin/build.gradle
  settings.gradle
Labels: in progress

#65 Generic code cleaning / utility method usage
  .gitignore
  config-builder/build.gradle
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/ListenPort.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/BundleDocumentBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ClusterPropertyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/EncassEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/Entity.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/EnvironmentPropertyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/FolderEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/IdentityProviderEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ListenPortEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyBackedServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/DependencyBundleLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/EncassLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/EntityLoaderRegistry.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/FolderLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/ListenPortLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/PolicyLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EncassLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/IdentityProviderLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/ListenPortLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/PolicyBackedServiceLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/ServiceLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/StaticPropertiesLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/entity/EntityTypes.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BuilderUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BundleElementNames.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/MappingActions.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/MappingProperties.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/json/JsonTools.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/policy/PolicyXMLElements.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/properties/PropertyConstants.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/xml/DocumentTools.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/xml/DocumentUtils.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/IdentityProviderEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ListenPortEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ServiceEntityBuilderTest.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
Labels: in progress, ready for review

#70 Adding support for stored passwords
  README.md
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/Bundle.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/StoredPassword.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/BundleEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/StoredPasswordEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EntityLoaderRegistry.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EnvironmentPropertiesLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/PropertiesLoaderBase.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/StaticPropertiesLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/StoredPasswordsLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/entity/EntityTypes.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BundleElementNames.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/StoredPasswordEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/StoredPasswordLoaderTest.java
  doc/stored-passwords.md
Labels: in progress

#53 Add Jdbc connection support
  README.md
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/Bundle.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/JdbcConnection.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/BundleEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/JdbcConnectionEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/bundle/loader/ListenPortLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EntityLoaderRegistry.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/JdbcConnectionLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/entity/EntityTypes.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BuilderUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BundleElementNames.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/JdbcConnectionEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ListenPortEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/StoredPasswordEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/JdbcConnectionLoaderTest.java
  doc/jdbc-connections.md
  doc/listen-ports.md
Labels: ready for review

#66 Adding the container-application to replace the apply-environment.sh script
  .travis.yml
  build.gradle
  config-builder/build.gradle
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/PropertiesLoaderBase.java
  doc/applying-environment.md
  environment-creator-application/build.gradle
  environment-creator-application/settings.gradle
  environment-creator-application/src/main/java/com/ca/apim/gateway/cagatewayconfig/Main.java
  gateway-developer-plugin/build.gradle
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageBuildException.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/Packager.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/GW7Builder.java
  gateway-developer-plugin/src/main/resources/scripts/apply-environment.sh
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-developer-plugin/src/test/resources/example-project-custom-organization/build.gradle
  gateway-developer-plugin/src/test/resources/example-project/build.gradle
  settings.gradle
Labels: in progress, ready for review
