Repository CAAPIM/gateway-developer-plugin, pull requests merged in 2018-08, with the labels that each got.

#55 adding in a semantic versioning plugin
  .travis.yml
  README.md
  build.gradle
  semantic-build-versioning.gradle
  settings.gradle
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ClusterPropertyEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EntityLoaderRegistry.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/StaticPropertiesLoader.java
  src/test/resources/example-project/src/main/gateway/config/static.properties
  src/test/resources/example-project/src/main/gateway/policy/example project/example.xml
Labels: in progress

#50 Feature/extract env
  README.md
  build.gradle
  doc/encapsulated-assertions.md
  doc/environment-properties.md
  doc/images/environment-properties/branch-on-db-type.png
  doc/images/environment-properties/branching-policy.png
  doc/images/environment-properties/cluster-properties.png
  doc/images/environment-properties/context-variables.png
  doc/images/environment-properties/create-cluster-property.png
  doc/images/environment-properties/db-type-context-variable-assertion.png
  doc/images/environment-properties/http-route-assertion.png
  doc/images/environment-properties/rate-limit-assertion.png
  doc/images/environment-properties/route-using-cluster-property.png
  doc/images/environment-properties/service-properties-env.png
  doc/images/environment-properties/service-properties.png
  doc/images/environment-properties/user-service-properties-env.png
  doc/policy-backed-services.md
  doc/services.md
  doc/static-properties.md
  src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/GatewayDeveloperPluginConfig.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/BuildBundleTask.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/BundleBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/BundleDocumentBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ClusterPropertyEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/EnvironmentBundleBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/EnvironmentPropertyEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ServiceEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EntityLoaderRegistry.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EnvironmentPropertiesLoader.java
  src/main/resources/scripts/apply-environment.sh
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/ServiceEntityBuilderTest.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/PolicyAndFolderLoaderTest.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/ServiceLoaderTest.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/util/IdGeneratorTest.java
  src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  src/test/resources/example-project-custom-organization/build.gradle
Labels: in progress

#58 Adding support for bind-only LDAP IP configuration
  doc/identity-providers.md
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/identityprovider/BindOnlyLdapIdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/identityprovider/IdentityProvider.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/identityprovider/IdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/beans/identityprovider/LdapIdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/BundleEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/IdentityProviderEntityBuilder.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/EntityLoaderRegistry.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/IdentityProviderLoader.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/util/xml/DocumentTools.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/IdentityProviderEntityBuilderTest.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/loader/IdentityProviderLoaderTest.java
  src/test/resources/example-project/src/main/gateway/config/identity-providers.yml
Labels: ready for review

#59 creating gw7 packaging task
  build.gradle
  src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageBuildException.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageTask.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/Packager.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/util/file/FileUtils.java
  src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/GW7Builder.java
  src/test/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/GW7BuilderTest.java
  src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
Labels: in progress, ready for review
