Repository CAAPIM/gateway-developer-plugin, pull requests merged in 2018-12, with the labels that each got.

#144 Miscellaneous fixes
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/FolderEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/EntityBundleLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ScheduledTaskLoader.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ScheduledTaskLoaderTest.java
  environment-creator-application/src/main/java/com/ca/apim/gateway/cagatewayconfig/BundleEnvironmentValidator.java
Labels: in progress

#148 139 - making folderPath final and modifying README
  README.md
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/GatewayExportPluginConfig.java
Labels: in progress

#147 Updating jackson version
  config-builder/build.gradle
Labels: ready for review

#152 Adding properties to encass entities
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Encass.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EncassEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/EncassLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/properties/PropertyConstants.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EncassEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/EncassLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EncassLoaderTest.java
Labels: in progress, ready for review

#154 Creating gradle task for generating environment bundles
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Policy.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/CertificatesLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderBase.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PolicyAndFolderLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PropertiesLoaderBase.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizeException.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizer.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/DeploymentBundleException.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCreationMode.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/MissingEnvironmentException.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/injection/ConfigBuilderModule.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/json/JsonTools.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/BundleFileBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/AuditPolicyLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/CassandraConnectionsLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/CertificatesLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderRegistryTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EnvironmentPropertiesLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PolicyAndFolderLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizerTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidatorTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/util/injection/ConfigBuilderModuleTest.java
  environment-creator-application/src/main/java/com/ca/apim/gateway/cagatewayconfig/EnvironmentCreatorApplication.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildDeploymentBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildEnvironmentBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/GatewayDeveloperPluginConfig.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/build.gradle
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/lib/my-bundle-1.0.00.bundle
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/settings.gradle
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/src/main/gateway/config/jdbc-connections-malformed.yml
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/src/main/gateway/config/jdbc-connections-wrong.yml
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/src/main/gateway/config/jdbc-connections.yml
  gateway-developer-plugin/src/test/resources/example-project-generating-environment/src/main/gateway/policy/example project/db-service.xml
Labels: in progress, ready for review
