Repository CAAPIM/gateway-developer-plugin, pull requests merged in 2019-02, with the labels that each got.

#180 Split import bundle task to a separate plugin
  gateway-connection-api/build.gradle
  gateway-connection-api/settings.gradle
  gateway-connection-api/src/main/java/com/ca/apim/gateway/connection/GatewayClient.java
  gateway-connection-api/src/main/java/com/ca/apim/gateway/connection/GatewayClientException.java
  gateway-connection-api/src/main/java/com/ca/apim/gateway/connection/GatewayConnectionProperties.java
  gateway-export-plugin/build.gradle
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExport.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundleTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/export/ExportTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/injection/ExportPluginModule.java
  gateway-import-plugin/build.gradle
  gateway-import-plugin/settings.gradle
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/CAGatewayImport.java
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/CAGatewayImportBase.java
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/tasks/ImportBundleTask.java
  settings.gradle
Labels: ready for review

#181 Remove gradle dependency due to publishing failure
  gateway-connection-api/build.gradle
  gateway-connection-api/src/main/java/com/ca/apim/gateway/connection/GatewayClient.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExport.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/config/GatewayExportConnectionProperties.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/export/ExportTask.java
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/CAGatewayImport.java
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/config/GatewayImportConnectionProperties.java
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/tasks/ImportBundleTask.java
Labels: in progress

#179 Loading environment from filesystem mounted files
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/EntityTypeRegistry.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EncassEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/FolderEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyBackedServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ScheduledTaskEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/FullBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/environment/EnvironmentConfigurationUtils.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EncassEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/FolderEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyBackedServiceEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ScheduledTaskEntityBuilderTest.java
  environment-creator-application/src/main/java/com/ca/apim/gateway/cagatewayconfig/EnvironmentCreatorApplication.java
  environment-creator-application/src/test/java/com/ca/apim/gateway/cagatewayconfig/EnvironmentCreatorApplicationTest.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildEnvironmentBundleTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/policy/PolicyXMLSimplifier.java
Labels: in progress, ready for review

#183 Repackage classes into config-builder module
  config-builder/build.gradle
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/connection/GatewayClient.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/connection/GatewayClientException.java
  gateway-connection-api/build.gradle
  gateway-connection-api/settings.gradle
  gateway-export-plugin/build.gradle
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/export/ExportTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/injection/ExportPluginModule.java
  gateway-import-plugin/build.gradle
  gateway-import-plugin/src/main/java/com/ca/apim/gateway/cagatewayimport/tasks/ImportBundleTask.java
  settings.gradle
Labels: in progress

#185 Bugfix/176 jms missing fields export
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/JmsDestinationDetail.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/JmsDestinationLoader.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/JmsDestinationLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/JmsDestinationLoaderTest.java
Labels: in progress, ready for review

#184 Allow env files directly located into mounted directory
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/CertificatesLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderBase.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PropertiesLoaderBase.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/file/FileUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/json/JsonTools.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EntityLoaderBaseTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PropertiesLoaderBaseTest.java
Labels: ready for review

#187 Refactoring gradle publishing configs
  .travis.yml
  build.gradle
  gradle/config/module.gradle
  gradle/config/publishing-config.gradle
  gradle/config/publishing-pom.gradle
Labels: in progress

#177 Environment entities directly linked to services fail the startup
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ListenPortEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/EntityBundleLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ListenPortLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleCache.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/injection/ConfigBuilderModule.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ListenPortEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ListenPortLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/util/TestUtils.java
Labels: in progress
