Repository CAAPIM/gateway-developer-plugin, pull requests merged in 2019-01, with the labels that each got.

#149 Add service/policy names to service properties and context variable
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/ContextVariableEnvironmentProperty.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/EnvironmentProperty.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/GlobalEnvironmentProperty.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/ServiceEnvironmentProperty.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ClusterPropertyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizer.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BuilderUtils.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ClusterPropertyEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/EnvironmentPropertiesLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizerTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidatorTest.java
  environment-creator-application/src/test/java/com/ca/apim/gateway/cagatewayconfig/EnvironmentCreatorApplicationTest.java
  environment-creator-application/src/test/resources/templatized-bundles/my-bundle.req.bundle
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ClusterPropertyLinker.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/PolicyLinker.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ServiceLinker.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/WriterHelper.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/policy/PolicyXMLSimplifier.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExportTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ClusterPropertyLinkerTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ServiceLinkerTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/util/policy/PolicyXMLSimplifierTest.java
Labels: in progress, ready for review

#160 Fix transitive assertion dependency packaging
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/BundleFileBuilder.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/BundleFileBuilderTest.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildDeploymentBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/ProjectDependencyUtils.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/gw7/PackageTask.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/build.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/lib/Test-1.0.0.jar
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-a/build.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-a/settings.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-a/src/main/gateway/policy/common/my-common-policy.xml
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-b/build.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-b/settings.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-b/src/main/gateway/policy/common/dependent.xml
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-c/build.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/project-c/settings.gradle
  gateway-developer-plugin/src/test/resources/multi-project-with-assertions-dependencies/settings.gradle
Labels: ready for review

#163 156 - Handle service and policy entities with duplicate names
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EntityBuilderHelper.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/MappingProperties.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilderTest.java
Labels: ready for review

#162 Multimodule project and appliance GWs miscellaneous fixes
  build.gradle
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ClusterPropertyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/EncassEntityBuilder.java
  docker-compose.yml
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/GatewayDeveloperPluginConfig.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-developer-plugin/src/test/resources/multi-project/project-c/build.gradle
Labels: in progress

#168 Feature/159 Ignore unsupported files inside policy directories
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PolicyAndFolderLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/policy/PolicyConverterRegistry.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PolicyAndFolderLoaderTest.java
Labels: in progress, ready for review

#138 Add support for JMS Destination entity.
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/InboundJmsDestinationDetail.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/JmsDestination.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/JmsDestinationDetail.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/OutboundJmsDestinationDetail.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/BuilderConstants.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JdbcConnectionEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/JmsDestinationLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizer.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/entity/EntityTypes.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BundleElementNames.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/policy/PolicyXMLElements.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/properties/PropertyConstants.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JdbcConnectionEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/JmsDestinationLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/JmsDestinationLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleDetemplatizerTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/util/TestUtils.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/JmsDestinationFilter.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/JdbcConnectionLinker.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/JmsDestinationLinker.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/LinkerConstants.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/policy/PolicyXMLSimplifier.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/JmsDestinationFilterTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/JdbcConnectionLinkerTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/JmsDestinationLinkerTest.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/util/TestUtils.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/util/policy/PolicyXMLSimplifierTest.java
Labels: ready for review

#171 Tasks for generate and install a full bundle into an existing gateway
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyBackedServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/EntityBundleLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/policy/XMLPolicyConverter.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/BundleEnvironmentValidator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/FullBundleCreator.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/TemplatizedBundle.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/environment/EnvironmentConfigurationUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/file/DocumentFileUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/file/FileUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/ConnectionUtils.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/injection/ConfigBuilderModule.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/xml/DocumentTools.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/xml/DocumentUtils.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PolicyEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/PolicyAndFolderLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/policy/XMLPolicyConverterTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/util/file/DocumentFileUtilsTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/util/injection/ConfigBuilderModuleTest.java
  environment-creator-application/src/test/java/com/ca/apim/gateway/cagatewayconfig/EnvironmentCreatorApplicationTest.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildEnvironmentBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/BuildFullBundleTask.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java
  gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/ProjectDependencyUtils.java
  gateway-developer-plugin/src/test/java/com/ca/apim/gateway/capublisherplugin/CAGatewayDeveloperTest.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExport.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/config/GatewayConnectionProperties.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/config/GatewayExportPluginConfig.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/export/ExportTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/importing/ImportBundleTask.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/http/GatewayClient.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/util/injection/ExportPluginModule.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/PolicyWriterTest.java
Labels: in progress, ready for review

#175 Skipping export task if folderPath is not specified
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/config/GatewayExportPluginConfig.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundleTask.java
Labels: ready for review

#172 Adding support to link listen ports with private keys
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/ListenPort.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ListenPortEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/PrivateKeyEntityBuilder.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ListenPortLoader.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/gateway/BundleElementNames.java
  config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/properties/PropertyConstants.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ListenPortEntityBuilderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ListenPortLoaderTest.java
  config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/ListenPortLoaderTest.java
  gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ListenPortLinker.java
  gateway-export-plugin/src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/ListenPortLinkerTest.java
Labels: in progress, ready for review
